### ISSUE TITLE
Publish scout on PyPi

### ISSUE THREAD

**Issue by ypid** [sdrfnord/scripts#1]
Hey, it would be great to have scout on https://pypi.python.org. The only thing is that the name scout is already taken. I have been thinking more like `sshunlock`.

**Comment by sdrfnord** [comment]
I don't have any experience with putting python scripts on pipy and I don't have much time to get into it. If you have time to do it feel free to do so. About the name, I guess sshunlock should do.

**Comment by ypid** [comment]
Thanks for your feedback. Well, I see some potential in the script and already hacked on it a far bit the last days to make it fit my usecase. As for the name I changed my mind and would now go with FDEunlock. So, you are ok with me taking over? I would like to get the project on the same standard as the other Python packages I am currently maintaining (ref: [hc](https://gitlab.com/ypid/hc), [yaml4rst](https://github.com/ypid/yaml4rst)). Also, I would like to change from GPL-3.0+ to AGPL-3.0.

**Comment by sdrfnord** [comment]
> So, you are ok with me taking over?

Looking at your other projects I am sure you can do a better job then I can with maintaining/continuing this. So, yes.

> Also, I would like to change from GPL-3.0+ to AGPL-3.0.

The license does not require me approving to this when I get it correctly.  I am ok with either one.

Looking forward to hand over maintenance to you, thanks @ypid :wink:

**Comment by ypid** [comment]
> Looking forward to hand over maintenance to you, thanks @ypid :wink:

You are welcome :wink:

All done and tested: https://gitlab.com/ypid/fdeunlock, https://github.com/ypid/fdeunlock

Enjoy :-)

Can you update the readme for scout to point to the fork?

**Comment by sdrfnord** [comment]
I just found the time to check it out and test it. Awesome work, bro!!!! I deprecated my scout and point to FDEunlock instead.

**Comment by ypid** [comment]
Thanks, you are welcome :)
